---
# tasks file for prod
- name: install tomcat
  apt: name=tomcat8 state=installed update_cache=true

- name: Copy war_file
  copy: src=hello-1.0.war dest=/var/lib/tomcat8/webapps/
  notify: restart tomcat
