---
- name: install nginx
  hosts: all
  become: yes

  vars:
    src_folder: ./
    dest_folder: /var/www/html

  tasks:
    - name: Ensure nginx is present
      apt:
        name: nginx
        state: present

    - name: templates index.html
      template: src={{ src_folder }}/index.j2 dest={{ dest_folder }}/index.html
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
