version: '2'
services:
  web:
    image: nginx:latest
    container_name: web
    links:
      - php
    ports: 
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    build: php-7.0-fpm-custom
    container_name: php
    environment: 
      - TYPO3_CONTEXT=Development/Docker
    links:
      - db
      - redis
    volumes:
      - ./htdocs:/var/www/html
  db:
    image: mariadb:10.1
    container_name: database
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql:/var/lib/mysql/
  redis:
    image: redis:latest
    container_name: redis-cache   
