---
- name: webserver confoguration
  hosts: build
  become: yes

  roles:
    - common
    - webserver
    - security


- name: db congiguration
  hosts: prod
  become: yes

  roles:
   - security
   - common
