# сборка происходит командой docker build --no-cache --build-arg REPO=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git -t mvn_build -f Dockerfile_build .


FROM maven:3-jdk-7-slim
ARG REPO
WORKDIR /srv
RUN apt-get update && apt-get install -y git 
RUN git clone ${REPO} . && mvn package 



